jobs:
  install-helm-chart:
    executor: gcp-gke/default
    parameters:
      cluster-name:
        description: "Cluster name"
        type: string
    steps:
      - gcp-gke/install
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: devops-p4
          perform-login: true
      - helm/install-helm-chart:
          chart: ./charts/ipfs-cluster
          helm-version: v3.2.4
          release-name: twy
version: 2.1
orbs:
  helm: circleci/helm@1.2.0
  gcp-gke: circleci/gcp-gke@1.2.0
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  deployment:
    # Run the welcome/run job in its own container
    jobs:
      - install-helm-chart:
          cluster-name: twy-staging

