jobs:
  deploy-to-staging:
    executor: gcp-gke/default
    parameters:
      cluster-name:
        description: "Cluster name"
        type: string
    steps:
      - checkout
      - gcp-gke/install
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: twy-staging
          perform-login: true
      - helm/install-helm-client:
          version: v3.2.4
      - run:
          name: Install helm-helmfile
          command: |
              wget https://github.com/roboll/helmfile/releases/download/v0.138.7/helmfile_linux_arm64
              ./helmfile --environment staging template
version: 2.1
orbs:
  helm: circleci/helm@1.2.0
  gcp-gke: circleci/gcp-gke@1.2.0
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  deployment:
    # Run the welcome/run job in its own container
    jobs:
      - deploy-to-staging:
          cluster-name: twy-staging

